### ISSUE TITLE
Ensemble runs

### ISSUE THREAD

**Issue by ali-ramadhan** [ali-ramadhan/lagrangian-microbes#22]
Run for a full year:
* Vary # of particles: 10,000 100,000 1,000,000
* Vary diffusivity: 0, low κ (fuzzy motion, Kh=20), medium κ (Kh=100), large κ (get kicked out of eddies, Kh=500)
* Vary the interaction: netural (change p=0.5, 0.7, 0.9, 0.999, 1), non-neutral (pRS=0.501, 0.51, 0.6, 0.7, 0.99)

**Comment by gregbritten** [comment]
I still like these parameters a lot. I suspect we'll see a big difference in the competitive exclusion timescale as a function of p for different diffusivities, which will be really interesting to see..

**Comment by ali-ramadhan** [comment]
Awesome! I was able to figure out the performance issue with adding diffusivity so I'll start running these simulations.

**Comment by gregbritten** [comment]
As for analyses, there are a few I'd like to try. The simplest is to look at the characteristic timescales and size of the fluctuations in total population size, like the plots you made a while back with R,P,S as three time series of population size.  There are a few expectations I'd like to see play out: we should see smaller fluctuations with higher diffusion, should also see smaller fluctuations for more 'symmetric' neutral interactions, and we should see faster competitive exclusion for non-neutral cases with higher diffusion..

The spatial analysis will have the same character.. I just have to think a little more about how exactly to characterize things. We want something like 'the probably of a random bug being the same type as a function of distance', which is bit of a modification of the histograms we made before. I think we need to make some distance bins and compute (#pairs the same)/(total # pairs) for a range of distance bins..

**Comment by ali-ramadhan** [comment]
I'm adding an analysis module that should produce a species count time series plot with every run. We can add more complex analyses as we figure them out but should be easy to add new ones!

**Comment by ali-ramadhan** [comment]
@gregbritten Simulations are running smoothly but might be worth discussing how we set the interaction length scale. Some of the simulations seem to be a little wacky.

Also what would be useful for you for the CBIOMES meeting? We can get that out of the way and then worry about running the full suite of simulations.

**Comment by gregbritten** [comment]
Hey, I think I'll just show a few time series plots at the meeting. Are the simulations running with all the different parameter settings outlined above? I wonder if there is a nice comparison in there where would could show the different exclusion timescales for different non-neutral interactions, maybe at a couple different settings for diffusion.. 

As for the interaction length scale, I totally agree we will need to think more about it.. there are all kinds of processes tied up in it.. What kind of wacky-ness are you seeing?

**Comment by gregbritten** [comment]
I'm seeing all the file output in /nfs/cnhlab004/alir/lagrangian_microbes_output but I'm wondering what the folder codes mean: NX_KhX_pX_aX. What is the 'a'?

**Comment by ali-ramadhan** [comment]
> Hey, I think I'll just show a few time series plots at the meeting. Are the simulations running with all the different parameter settings outlined above?

Yup! But they take a while to run until I can maybe speed things up more.

> I'm seeing all the file output in /nfs/cnhlab004/alir/lagrangian_microbes_output but I'm wondering what the folder codes mean: NX_KhX_pX_aX. What is the 'a'?

Ah sorry. E.g. `N10000_Kh20.0_p0.5_a0.6` means
* N = 10,000 particles/microbes,
* a horizontal isotropic _eddy_ diffusivity of roughly Kh = 20 m^2/s,
* p = 0.5 in the rock-paper-scissors interaction, and
* one of the interactions, the scissors-paper interaction, is imbalanced by a. So the probability of scissors winning is now p + a.

So p = 0.5, a = 0.1 would mean you have `pRS, pPR, pSP = 0.5, 0.5, 0.6`.

PS: Just realized I made a huge mistake! `a` should be less than 0.5 but I set it to 0,6, 0.7, etc. which would partially explain why I'm seeing weird results as I was setting some values of p to be larger than 1... I'll start re-running the simulations lol.

**Comment by ali-ramadhan** [comment]
> As for the interaction length scale, I totally agree we will need to think more about it.. there are all kinds of processes tied up in it.. What kind of wacky-ness are you seeing?

Using ~5 km (0.05 deg lol) for 10,000 particles but will probably decrease to ~500 m for 1,000,000 particles. Maybe ~1.5 km for 100,000 particles.

Most of the wacki-ness was probably just me not setting `a` correctly.

Although I accidentally ran a 1,000,000 microbe simulation overnight with a 5 km interaction length and woke up to find it resolving ~50 million interactions every time step lol.

**Comment by ali-ramadhan** [comment]
> I wonder if there is a nice comparison in there where would could show the different exclusion timescales for different non-neutral interactions, maybe at a couple different settings for diffusion..

I'll run these simulations so we can get a few data points for this.

I'll go with N=10k, 100k, and low+high diffusion (Kh=20, 500), and small+large asymmetry (a = 0.01, 0.1):
```
python rock_paper_scissors_argparse.py -N 10000 -K 20 -p 0.5 -a 0.01 -d ~/cnhlab004/lagrangian_microbes_output/
python rock_paper_scissors_argparse.py -N 10000 -K 20 -p 0.5 -a 0.1 -d ~/cnhlab004/lagrangian_microbes_output/
python rock_paper_scissors_argparse.py -N 10000 -K 500 -p 0.5 -a 0.01 -d ~/cnhlab004/lagrangian_microbes_output/
python rock_paper_scissors_argparse.py -N 10000 -K 500 -p 0.5 -a 0.1 -d ~/cnhlab004/lagrangian_microbes_output/
python rock_paper_scissors_argparse.py -N 100000 -K 20 -p 0.5 -a 0.01 -d ~/cnhlab004/lagrangian_microbes_output/
python rock_paper_scissors_argparse.py -N 100000 -K 20 -p 0.5 -a 0.1 -d ~/cnhlab004/lagrangian_microbes_output/
python rock_paper_scissors_argparse.py -N 100000 -K 500 -p 0.5 -a 0.01 -d ~/cnhlab004/lagrangian_microbes_output/
python rock_paper_scissors_argparse.py -N 100000 -K 500 -p 0.5 -a 0.1 -d ~/cnhlab004/lagrangian_microbes_output/
```

**Comment by ali-ramadhan** [comment]
All of these are running or in the pipeline thanks to PR #34 so I'm going to close this issue.
